requirePragma: false
arrowParens: "avoid"
printWidth: 120
singleQuote: true
useTabs: false
tabWidth: 4
bracketSpacing: true
quoteProps: "as-needed"
endOfLine: "lf"
semi: false
trailingComma: "es5"
htmlWhitespaceSensitivity: "ignore"