INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('actionTokenGeneratedByAdminLifespan', '43200', 'pcmr');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('actionTokenGeneratedByUserLifespan', '300', 'pcmr');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('bruteForceProtected', 'false', 'master');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('bruteForceProtected', 'false', 'pcmr');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('clientOfflineSessionIdleTimeout', '0', 'pcmr');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('clientOfflineSessionMaxLifespan', '0', 'pcmr');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('clientSessionIdleTimeout', '0', 'pcmr');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('clientSessionMaxLifespan', '0', 'pcmr');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('displayName', 'Keycloak', 'master');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('displayNameHtml', '<div class="kc-logo-text"><span>Keycloak</span></div>', 'master');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('failureFactor', '30', 'master');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('failureFactor', '30', 'pcmr');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('maxDeltaTimeSeconds', '43200', 'master');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('maxDeltaTimeSeconds', '43200', 'pcmr');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('maxFailureWaitSeconds', '900', 'master');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('maxFailureWaitSeconds', '900', 'pcmr');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('minimumQuickLoginWaitSeconds', '60', 'master');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('minimumQuickLoginWaitSeconds', '60', 'pcmr');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('offlineSessionMaxLifespan', '5184000', 'master');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('offlineSessionMaxLifespan', '5184000', 'pcmr');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('offlineSessionMaxLifespanEnabled', 'false', 'master');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('offlineSessionMaxLifespanEnabled', 'false', 'pcmr');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('permanentLockout', 'false', 'master');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('permanentLockout', 'false', 'pcmr');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('quickLoginCheckMilliSeconds', '1000', 'master');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('quickLoginCheckMilliSeconds', '1000', 'pcmr');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('waitIncrementSeconds', '60', 'master');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('waitIncrementSeconds', '60', 'pcmr');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('webAuthnPolicyAttestationConveyancePreference', 'not specified', 'pcmr');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('webAuthnPolicyAttestationConveyancePreferencePasswordless', 'not specified', 'pcmr');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('webAuthnPolicyAuthenticatorAttachment', 'not specified', 'pcmr');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('webAuthnPolicyAuthenticatorAttachmentPasswordless', 'not specified', 'pcmr');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('webAuthnPolicyAvoidSameAuthenticatorRegister', 'false', 'pcmr');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('webAuthnPolicyAvoidSameAuthenticatorRegisterPasswordless', 'false', 'pcmr');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('webAuthnPolicyCreateTimeout', '0', 'pcmr');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('webAuthnPolicyCreateTimeoutPasswordless', '0', 'pcmr');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('webAuthnPolicyRequireResidentKey', 'not specified', 'pcmr');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('webAuthnPolicyRequireResidentKeyPasswordless', 'not specified', 'pcmr');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('webAuthnPolicyRpEntityName', 'keycloak', 'pcmr');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('webAuthnPolicyRpEntityNamePasswordless', 'keycloak', 'pcmr');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('webAuthnPolicyRpId', '', 'pcmr');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('webAuthnPolicyRpIdPasswordless', '', 'pcmr');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('webAuthnPolicySignatureAlgorithms', 'ES256', 'pcmr');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('webAuthnPolicySignatureAlgorithmsPasswordless', 'ES256', 'pcmr');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('webAuthnPolicyUserVerificationRequirement', 'not specified', 'pcmr');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('webAuthnPolicyUserVerificationRequirementPasswordless', 'not specified', 'pcmr');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('_browser_header.contentSecurityPolicy', 'frame-src ''self''; frame-ancestors ''self''; object-src ''none'';', 'master');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('_browser_header.contentSecurityPolicy', 'frame-src ''self''; frame-ancestors ''self''; object-src ''none'';', 'pcmr');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('_browser_header.contentSecurityPolicyReportOnly', '', 'master');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('_browser_header.contentSecurityPolicyReportOnly', '', 'pcmr');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('_browser_header.strictTransportSecurity', 'max-age=31536000; includeSubDomains', 'master');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('_browser_header.strictTransportSecurity', 'max-age=31536000; includeSubDomains', 'pcmr');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('_browser_header.xContentTypeOptions', 'nosniff', 'master');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('_browser_header.xContentTypeOptions', 'nosniff', 'pcmr');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('_browser_header.xFrameOptions', 'SAMEORIGIN', 'master');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('_browser_header.xFrameOptions', 'SAMEORIGIN', 'pcmr');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('_browser_header.xRobotsTag', 'none', 'master');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('_browser_header.xRobotsTag', 'none', 'pcmr');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('_browser_header.xXSSProtection', '1; mode=block', 'master');
INSERT INTO keycloak.REALM_ATTRIBUTE (NAME, VALUE, REALM_ID) VALUES ('_browser_header.xXSSProtection', '1; mode=block', 'pcmr');