spring:
  datasource:
    url: jdbc:mariadb://${PCMR_MYSQL_HOST}:${MYSQL_DB_PORT}/${PCMR_MYSQL_DATABASE}
    username: ${PCMR_MYSQL_USER}
    password: ${PCMR_MYSQL_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        hbm2ddl:
          delimiter: ';'
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: ./build/schema/schema.sql
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  error:
    include-message: always
  port: ${PCMR_SERVER_PORT}

keycloak:
  realm: ${PCMR_KEYCLOAK_REALM}
  auth-server-url: ${PCMR_AUTH_SERVER_URL}
  resource: ${PCMR_RESOURCE}
  bearer-only: true
  principal-attribute: preferred_username
  cors: true